SITES = [
    {
        "name": "AIG損保 ニュースリリース",
        "url": "https://www.aig.co.jp/sonpo/company/news",
        "base_url": "https://www.aig.co.jp",
        "xpath": "/html/body/div[1]/div[1]/div/div[3]/div/div[3]/ul",
        "extractor": "aig",
    },
    {
        "name": "損保ジャパン ニュースリリース",
        "url": "https://www.sompo-japan.co.jp/",
        "base_url": "https://www.sompo-japan.co.jp",
        "xpath": '//*[@id="contentswrapper"]/div[5]',
        "extractor": "sompo_japan",
    },
    {
        "name": "あいおいニッセイ同和損保 お知らせ・ニュースリリース",
        "url": "https://www.aioinissaydowa.co.jp/",
        "base_url": "https://www.aioinissaydowa.co.jp",
        "xpath": "//section[contains(@class,'p-top-spread')]",
        "extractor": "aioi",
    },
    {
        "name": "アニコム損保 トピックス",
        "url_template": "https://www.anicom-sompo.co.jp/topics/{year}/",
        "base_url": "https://www.anicom-sompo.co.jp",
        "xpath": '//*[@id="main"]',
        "extractor": "anicom",
    },
    {
        "name": "アニコム損保 ニュースリリース",
        "url_template": "https://www.anicom-sompo.co.jp/news-release/{year}/",
        "base_url": "https://www.anicom-sompo.co.jp",
        "xpath": '//*[@id="main"]',
        "extractor": "anicom",
    },
    {
        "name": "エイチ･エス損保 お知らせ",
        "url": "https://www.hs-sonpo.co.jp/",
        "base_url": "https://www.hs-sonpo.co.jp",
        "xpath": '//*[@id="frontpage"]/main/section[2]',
        "extractor": "hs_sonpo",
    },
    {
        "name": "ＳＢＩ損保 ニュースリリース",
        "url": "https://www.sbisonpo.co.jp/company/",
        "base_url": "https://www.sbisonpo.co.jp",
        "xpath": '//*[@id="wrapper"]/div[4]/div/div[5]/div/div/div[1]',
        "extractor": "sbi_sonpo",
    },
    {
        "name": "ＳＢＩ損保 お知らせ",
        "url": "https://www.sbisonpo.co.jp/company/",
        "base_url": "https://www.sbisonpo.co.jp",
        "xpath": '//*[@id="wrapper"]/div[4]/div/div[5]/div/div/div[2]',
        "extractor": "sbi_sonpo",
    },
    {
        "name": "ドコモ損保 お知らせ",
        "url": "https://www.docomo-sompo.com/news/",
        "base_url": "https://www.docomo-sompo.com",
        "xpath": '//*[@id="main"]/div[2]/div/div/ul',
        "extractor": "docomo_sompo",
    },
    {
        "name": "キャピタル損保 お知らせ",
        "url": "https://www.capital-sonpo.co.jp/",
        "base_url": "https://www.capital-sonpo.co.jp",
        "xpath": '//*[@id="Contents"]/div/div[3]/div/dl',
        "extractor": "capital_sonpo",
    },
    {
        "name": "共栄火災 お知らせ",
        "url": "https://www.kyoeikasai.co.jp/",
        "base_url": "https://www.kyoeikasai.co.jp",
        "xpath": '//*[@id="main"]/div[1]/section[1]/div/div/div[2]',
        "extractor": "kyoei_kasai",
    },
    {
        "name": "さくら損保 お知らせ",
        "url": "https://www.sakura-ssi.co.jp/",
        "base_url": "https://www.sakura-ssi.co.jp",
        "xpath": '//*[@id="home"]/div[2]/section[6]/div/ul/div/div/ul',
        "extractor": "sakura_sonpo",
    },
    {
        "name": "ジェイアイ お知らせ",
        "url": "https://www.jihoken.co.jp/",
        "base_url": "https://www.jihoken.co.jp",
        "xpath": '//*[@id="top-info"]/ul',
        "extractor": "jihoken",
    },
    {
        "name": "全管協れいわ損保 お知らせ",
        "url": "https://www.zkreiwa-sonpo.co.jp/",
        "base_url": "https://www.zkreiwa-sonpo.co.jp",
        "xpath": '//*[@id="post-98"]/div/div[2]/ul',
        "extractor": "zkreiwa_sonpo",
    },
    {
        "name": "ソニー損保 お知らせ",
        "url": "https://from.sonysonpo.co.jp/topics/information/N0086000.html",
        "base_url": "https://from.sonysonpo.co.jp",
        "xpath": '//div[contains(@class,"information-list2")]/ul',
        "extractor": "sony_sonpo",
    },
    {
        "name": "ソニー損保 自然災害等のお知らせ",
        "url": "https://from.sonysonpo.co.jp/topics/information/N0086000.html",
        "base_url": "https://from.sonysonpo.co.jp",
        "xpath": '//div[contains(@class,"archiveBox")]/ul[contains(@class,"information-list")]',
        "extractor": "sony_sonpo",
    },
    {
        "name": "SOMPOダイレクト 大切なお知らせ",
        "url": "https://news-ins-saison.dga.jp/topics/?type=important",
        "base_url": "https://news-ins-saison.dga.jp",
        "xpath": '//ul[contains(@class,"p-link-news")]',
        "extractor": "sompo_direct",
    },
    {
        "name": "SOMPOダイレクト ニュースリリース",
        "url": "https://news-ins-saison.dga.jp/topics/?type=news",
        "base_url": "https://news-ins-saison.dga.jp",
        "xpath": '//ul[contains(@class,"p-link-news")]',
        "extractor": "sompo_direct",
    },
]
